---
- hosts: geth
  become: yes
  become_method: sudo
  tasks:
    - name: include geth_base
      include: geth_base.yml
    
    - name: create geth directory
      file:
        state: directory
        path: "{{ mainnet_datadir }}"
        owner: ether
        group: ether
        mode: 0755

    - name: symlink chaindata to /data
      file:
        state: link
        path: /home/{{ geth_user }}/.ethereum/geth
        src: "{{ mainnet_datadir }}"

    - name: install service file
      template:
        src: templates/geth.service
        dest: /etc/systemd/system/multi-user.target.wants/geth.service
        owner: root
        group: root
        mode: 0644

    - name: reload systemd
      shell: systemctl daemon-reload

    - name: ensure geth service started
      service: 
        name: geth
        state: restarted

    # Checks for an account.  1 for no accounts, 0 for accounts found
    - name: check for an account
      shell: geth account list 2>&1 | grep "No etherbase" | wc -l
      register: account_check

    - name: if no account, create one
      shell: "geth account create --datadir {{ ropsten_datadir }} --password {{ geth_etherbase_password }}"
      when: mainnet_etherbase_password is defined and account_check.stdout == 1