---
- hosts: geth_ropsten
  become: yes
  become_method: sudo
  tasks:
    - name: include geth_base
      include: geth_base.yml

    - name: include geth vars
      include_vars: 
        file: vars/geth.yml

    - name: create geth directory
      file:
        state: directory
        path: "{{ ropsten_datadir }}"
        owner: ether
        group: ether
        mode: 0755

    - name: symlink chaindata to /data
      file:
        state: link
        path: /home/{{ geth_user }}/.ethereum/testnet
        src: "{{ ropsten_datadir }}"

    - name: install service file
      template:
        src: templates/geth-ropsten.service
        dest: /etc/systemd/system/multi-user.target.wants/geth-ropsten.service
        owner: root
        group: root
        mode: 0644

    - name: reload systemd
      shell: systemctl daemon-reload

    - name: ensure geth service started
      service: 
        name: geth-ropsten
        state: restarted

    # Checks for an account.  1 for no accounts, 0 for accounts found
    - name: check for an account
      shell: geth account list 2>&1 | grep "No etherbase" | wc -l
      register: account_check

    - name: if no account, create one
      shell: "geth account create --datadir {{ ropsten_datadir }} --password {{ geth_etherbase_password }}"
      when: ropsten_etherbase_password is defined and account_check.stdout == 1

    - name: ensure RPC access allowed
      firewalld:
        state: enabled
        zone: public
        port: "{{ ropsten_rpcport }}"
        permanent: true
      when: ropsten_rpcport is defined and ropsten_rpcpublic == true and firewall_state.stdout == 'running'